name: Publish NPM package

on:
  push:
    branches:
      - main

env:
  BUILD_STAGE_IMAGE_TAG: docker.pkg.github.com/${{ github.repository }}/build-cli:${{ github.sha }}
  NPM_DEPLOY_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CI_PUBLIC_EMAIL: ${{ secrets.CI_PUBLIC_EMAIL }}
  CI_PUBLIC_ORG_NAME: ${{ secrets.CI_PUBLIC_ORG_NAME }}
  GIT_COMMIT_HASH: ${{ github.sha }}

defaults:
  run:
    shell: bash
    working-directory: ./

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to GitHub Package Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Process building
        run: docker-compose build --force-rm build_service
      - name: Push result image to private Docker Registry
        run: docker image ls && docker-compose push build_service

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to GitHub Package Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Process NPM package deploy
        run: echo "${BUILD_STAGE_IMAGE_TAG}" && docker-compose build --force-rm deploy_service
